name: iso_build
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 2 * * *'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
      - 
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          release_name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_id: ${{ steps.release.outputs.id }}

  release:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        EDITION: [gnome]
        BRANCH: [unstable]
        SCOPE: [full,minimal]
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - 
        name: checkout
        uses: actions/checkout@v2
        with:
          repository: manjaro-plasma/iso-profiles
          token: "${{ secrets.GITHUB_TOKEN }}"
          path: 'iso-profiles'
      -
        name: build
        env:
          EDITION: ${{ matrix.EDITION }}
          BRANCH: ${{ matrix.BRANCH }}
          SCOPE: ${{ matrix.SCOPE }}
        run: |
          mkdir -p manjaro-tools pkg-cache iso

          [ "$SCOPE" == "minimal" ] && unset SCOPE

          docker run -v --rm --privileged \
          -e EDITION=$EDITION \
          -e BRANCH=$BRANCH \
          -e FULL=${SCOPE} \
          -v $PWD/pkg-cache:/var/cache/pacman/pkg/ \
          -v $PWD/iso-profiles:/builder/iso-profiles/ \
          -v $PWD/manjaro-tools:/var/lib/manjaro-tools/ \
          -v $PWD/iso:/var/cache/manjaro-tools/iso \
          -t manjarosway/manjaro-iso
          
          docker stop $(docker ps -a -q)
          docker rm -vf $(docker ps -a -q)
          docker rmi -f $(docker images -a -q)
          
          FILE_PATH=$(find ./iso -type f -name "*.iso" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
          zip -s 1650m $(basename $FILE_PATH).zip $FILE_PATH
          ls -lasih .
          sha256sum $(basename $FILE_PATH).z* > $(basename $FILE_PATH).sha256

          echo "FILE_PATH=$(basename $FILE_PATH)" >> $GITHUB_ENV
          echo "FILE_SHA256=$(basename $FILE_PATH).sha256" >> $GITHUB_ENV
          
          FILE_PKG=$(find ./iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
          cp -v $FILE_PKG .

          echo "FILE_PKG=$(basename $FILE_PKG)" >> $GITHUB_ENV
      - 
        id: upload_release_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_PATH }}.zip
          asset_name: ${{ env.FILE_PATH }}.zip
          asset_content_type: application/zip
      - 
        id: upload_release_z01
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_PATH }}.z01
          asset_name: ${{ env.FILE_PATH }}.z01
          asset_content_type: application/zip
      - 
        id: upload_sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_SHA256 }}
          asset_name: ${{ env.FILE_SHA256 }}
          asset_content_type: text/plain
      - 
        id: upload_pkg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./${{ env.FILE_PKG }}
          asset_name: ${{ env.FILE_PKG }}
          asset_content_type: text/plain                 
      - 
        name: rollback_release
        if: failure()
        uses: author/action-rollback@stable
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
